### ISSUE TITLE
Missing Devdependencies

### ISSUE THREAD

**Issue by Gobleizer** [marios-retail-store/retail-app#29]
https://github.com/marios-retail-store/retail-app/blob/dc70f62fd1c654627c4d8f26845621610018b684/package.json#L24

Should nodemon be run in all environments? Be sure to organize your project's dependencies by development and production so that when installing production dependencies, your development modules won’t be included. https://nodejs.dev/learn/npm-dependencies-and-devdependencies

Right now your project is missing a separation between dev and prod dependencies.

**Comment by corneliusrenken** [comment]
https://github.com/marios-retail-store/retail-app/pull/58
